### PR TITLE
support different phases

### PR DESCRIPTION
**Pull request by philandstuff**
Currently we hardcode our phase banner to "ALPHA".  We should support
displaying a different phase depending on the phase of the register from
the register configuration.  A phase of "alpha" gives the alpha banner,
a phase of "beta" gives the beta banner, and a phase of anything
else (such as "live") removes the banner completely.

All our registers currently have the `alpha` phase so this won't change the appearance of any current register.

cc @psd @stephenjoe1 @robinwhittleton

Screenshots below generated locally by manually editing the phase input.
alpha:
screen shot 2016-02-09 at 15 10 17

beta: 
screen shot 2016-02-09 at 15 09 46

live: 
screen shot 2016-02-09 at 15 09 37

### CODE REVIEW

**Comment by robinwhittleton** [comment]
Can we go with `.phase-banner-alpha` and `.phase-banner-beta` (as per [elements](http://govuk-elements.herokuapp.com/alpha-beta-banners/))?

**Comment by philandstuff** [comment]
@robinwhittleton done

**Comment by robinwhittleton** [comment]
LGTM apart from that.

**Comment by stephenjoe1** [comment]
Looks good to me too.

**Pull request merged**
